FROM python:3

RUN pip install --upgrade pip
RUN pip install pip-tools

RUN adduser -D troncs
USER troncs
WORKDIR /apps/troncs

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

COPY --chown=troncs:troncs requirements.in .
RUN pip-compile --user --upgrade
RUN pip install --user -r requirements.txt

COPY --chown=troncs:troncs . .