FROM python:3

WORKDIR /apps/troncs

# create the app user
RUN groupadd -r app_troncs && useradd -r -g app_troncs -d /apps/troncs app_troncs

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

COPY requirements.in .
RUN pip install pip-tools
RUN pip-compile --upgrade
RUN pip install -r requirements.txt

COPY . .

# chown all the files to the app user
RUN chown -R app_troncs:app_troncs .

# change to the app user
USER app_troncs