version: '2'
services:
  troncs:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    container_name: troncs
    ports:
      - "8000:8000"
    volumes:
      - .:/apps/troncs
    restart: unless-stopped

