version: '2'
services:
  troncs:
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: gunicorn --bind 0.0.0.0:8000 website.wsgi
    container_name: troncs
    user: app_user:app_user
    volumes:
      - ./files:/apps/troncs/files:rw
    restart: unless-stopped
    networks:
      - proxy
    labels:
      - traefik.enable=true
      - traefik.http.routers.troncs.entrypoints=http
      - traefik.http.routers.troncs.rule=Host("troncs.champis.net")
      - traefik.http.middlewares.troncs-https-redirect.redirectscheme.scheme=https
      - traefik.http.routers.troncs.middlewares=troncs-https-redirect
      - traefik.http.routers.troncs-secure.entrypoints=https
      - traefik.http.routers.troncs-secure.rule=Host("troncs.champis.net")
      - traefik.http.routers.troncs-secure.tls=true
      - traefik.http.routers.troncs-secure.tls.certresolver=http
      - traefik.http.routers.troncs-secure.service=troncs
      - traefik.http.services.troncs.loadbalancer.server.port=8000
      - traefik.docker.network=proxy

networks:
  proxy:
    external: true
