FROM python:3

RUN pip install --upgrade pip
RUN pip install pip-tools

RUN adduser troncs
USER troncs
WORKDIR /apps/troncs

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

COPY --chown=troncs:troncs requirements.txt .
RUN pip install --user -r requirements.txt

ENV PATH="/apps/troncs/.local/bin:${PATH}"

COPY --chown=troncs:troncs . .