name: 🚀 CI

on: push

jobs:
  deploy:
    name: 🎉 Deploy
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
    - name: 📂 Push to server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        script: cd ${{ secrets.PROJECT_PATH }} && git pull origin master && docker-compose -f docker-compose.prod.yml up -d --build
